name: Review dog test

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: reviewdog/action-setup@v1
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
      - name: run tryAtEachStep
        run: lake exe tryAtEachStep "exact?" TryAtEachStepTest.lean --outfile try_at_each_step_output.json
        shell: bash
      - name: test
        run: |
          cat try_at_each_step_output.json
          ls
          pwd
        shell: bash
      - name: run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./convert_output_to_rdjson.sh | reviewdog -f=rdjson -reporter=github-pr-review
        shell: bash

