name: Review dog test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: reviewdog/action-setup@v1
      - uses: actions/checkout@v4
      - name: run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./convert_output_to_rdjson.sh | reviewdog -f=rdjson -reporter=github-pr-review
        shell: bash

